spring:
  application:
    name: discovery-eureka-ha
---
spring:
    profiles: peer1
server:
    port: 8761
eureka:
  instance:
    #指定当profile=peer1时 hostname=peer1
    hostname: peer1
  client:
    serviceUrl:
      #注册到peer2
      defaultZone: http://peer2:8762/eureka
---
spring:
  profiles: peer2
server:
  port: 8762
eureka:
  instance:
    #指定当profile=peer2时 hostname=peer2
    hostname: peer2
  client:
    serviceUrl:
      #注册到peer1
      defaultZone: http://peer1:8761/eureka
