server:
  port: 8031
spring:
  application:
    name: hystrix-turbine
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:8761/eureka
  instance:
    prefer-ip-address: true
turbine:
  app-config: feign-consumer-user-hystrix,feign-consumer-user-hystrix-fallback-factory
  cluster-name-expression: "'default'"