server:
  port: 8020
spring:
  application:
    name: feign-consumer-user-hystrix-fallback-factory
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:8761/eureka
  instance:
    prefer-ip-address: true
feign:
  hystrix:
    enabled: true